// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBfirst.Entity;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public string City { get; set; }
}